In [1]:
import pandas as pd
import numpy as np

In [2]:
merged_df = pd.read_csv('merged_df.csv')
merged_df

,matchday_nr,home_team_name,away_team_name,hist_home_team_win,hist_draw,hist_away_team_win,hist_goal_dif,season
0,1,Eintracht Frankfurt,FC Bayern München,24.0,22.0,56.0,-80.0,2022
1,1,Borussia Dortmund,Bayer 04 Leverkusen,36.0,22.0,30.0,19.0,2022
2,1,1. FC Union Berlin,Hertha BSC,4.0,3.0,3.0,0.0,2022
3,1,1. FC Köln,FC Schalke 04,39.0,22.0,27.0,27.0,2022
4,1,Borussia Mönchengladbach,TSG Hoffenheim,8.0,12.0,10.0,6.0,2022
...,...,...,...,...,...,...,...,...
4891,34,Hannover 96,FC Energie Cottbus,4.0,0.0,4.0,-1.0,2008
4892,34,Borussia Dortmund,VfL Wolfsburg,12.0,7.0,3.0,18.0,2008
4893,34,Hamburger SV,Karlsruher SC,15.0,17.0,12.0,14.0,2008
4894,34,VfL Bochum,FC Hansa Rostock,7.0,4.0,9.0,-3.0,2008
4895,34,Eintracht Frankfurt,MSV Duisburg,27.0,14.0,15.0,33.0,2008

In [3]:
data = pd.read_csv("data/bulidata.csv")
data.head()

,Unnamed: 0,MATCH_DATE,LEAGUE_NAME,SEASON,LEAGUE,FINISHED,LOCATION,VIEWER,MATCHDAY,MATCHDAY_NR,...,HOME_ICON,AWAY_TEAM_ID,AWAY_TEAM_NAME,AWAY_TEAM,AWAY_ICON,GOALS_HOME,GOALS_AWAY,DRAW,WIN_HOME,WIN_AWAY
0,0,2005-08-05 20:30:00,1. Fussball-Bundesliga 2005/2006,2005,bl1,True,München,NaN,1. Spieltag,1,...,https://i.imgur.com/jJEsJrj.png,87,Borussia Mönchengladbach,Gladbach,https://i.imgur.com/KSIk0Eu.png,3,0,0.0,1.0,0.0
1,1,2005-08-06 15:30:00,1. Fussball-Bundesliga 2005/2006,2005,bl1,True,Köln,NaN,1. Spieltag,1,...,https://upload.wikimedia.org/wikipedia/en/thum...,81,1. FSV Mainz 05,Mainz,https://upload.wikimedia.org/wikipedia/commons...,1,0,0.0,1.0,0.0
2,2,2005-08-06 15:30:00,1. Fussball-Bundesliga 2005/2006,2005,bl1,True,Duisburg,NaN,1. Spieltag,1,...,https://upload.wikimedia.org/wikipedia/en/c/c8...,16,VfB Stuttgart,Stuttgart,https://i.imgur.com/v0tkpNx.png,1,1,1.0,0.0,0.0
3,3,2005-08-06 15:30:00,1. Fussball-Bundesliga 2005/2006,2005,bl1,True,Hamburg,NaN,1. Spieltag,1,...,https://upload.wikimedia.org/wikipedia/commons...,79,1. FC Nürnberg,Nürnberg,https://upload.wikimedia.org/wikipedia/commons...,3,0,0.0,1.0,0.0
4,4,2005-08-06 15:30:00,1. Fussball-Bundesliga 2005/2006,2005,bl1,True,Wolfsburg,NaN,1. Spieltag,1,...,https://i.imgur.com/ucqKV4B.png,7,Borussia Dortmund,BVB,https://upload.wikimedia.org/wikipedia/commons...,2,2,1.0,0.0,0.0

In [4]:
def data_clean():
    data.columns = cc = [column.lower().replace(' ', '_') for column in data]

In [5]:
data_clean()
data.columns

Index(['unnamed:_0', 'match_date', 'league_name', 'season', 'league',
       'finished', 'location', 'viewer', 'matchday', 'matchday_nr',
       'home_team_id', 'home_team_name', 'home_team', 'home_icon',
       'away_team_id', 'away_team_name', 'away_team', 'away_icon',
       'goals_home', 'goals_away', 'draw', 'win_home', 'win_away'],
      dtype='object')

In [6]:
# Check unique team names in both datasets again
buli_home_teams = set(data['home_team_name'].unique())
buli_away_teams = set(data['away_team_name'].unique())
merged_home_teams = set(merged_df['home_team_name'].unique())
merged_away_teams = set(merged_df['away_team_name'].unique())

In [7]:
# Find differences in home team names between the datasets
home_teams_buli_not_merged = buli_home_teams - merged_home_teams
home_teams_merged_not_buli = merged_home_teams - buli_home_teams

In [8]:
# Find differences in away team names between the datasets
away_teams_buli_not_merged = buli_away_teams - merged_away_teams
away_teams_merged_not_buli = merged_away_teams - buli_away_teams

In [9]:
home_teams_buli_not_merged

{'Alemannia Aachen', 'Arminia Bielefeld'}

In [10]:
home_teams_merged_not_buli

{'1899 Hoffenheim',
 'Bayer 04 Leverkusen',
 'Bayern München',
 'DSC Arminia Bielefeld',
 'FC Augsburg 1907',
 'FSV Mainz 05',
 'Hertha BSC Berlin',
 'SV Werder Bremen',
 'Schalke 04',
 'Sport-Club Freiburg',
 'TSG Hoffenheim',
 'VfL Bochum 1848'}

In [11]:
away_teams_buli_not_merged

{'Alemannia Aachen', 'Arminia Bielefeld'}

In [12]:
away_teams_merged_not_buli

{'1899 Hoffenheim',
 'Bayer 04 Leverkusen',
 'Bayern München',
 'DSC Arminia Bielefeld',
 'FC Augsburg 1907',
 'FSV Mainz 05',
 'Hertha BSC Berlin',
 'SV Werder Bremen',
 'Schalke 04',
 'Sport-Club Freiburg',
 'TSG Hoffenheim',
 'VfL Bochum 1848'}

In [13]:
data['home_team_name'].unique()

array(['FC Bayern München', '1. FC Köln', 'MSV Duisburg', 'Hamburger SV',
       'VfL Wolfsburg', 'Werder Bremen', 'Hannover 96', 'FC Schalke 04',
       'Eintracht Frankfurt', 'Bayer Leverkusen',
       'Borussia Mönchengladbach', 'Borussia Dortmund', 'Hertha BSC',
       '1. FC Kaiserslautern', '1. FC Nürnberg', 'Arminia Bielefeld',
       'VfB Stuttgart', '1. FSV Mainz 05', 'FC Energie Cottbus',
       'Alemannia Aachen', 'VfL Bochum', 'Karlsruher SC',
       'FC Hansa Rostock', 'TSG 1899 Hoffenheim', 'SC Freiburg',
       'FC St. Pauli', 'FC Augsburg', 'SpVgg Greuther Fürth',
       'Fortuna Düsseldorf', 'Eintracht Braunschweig', 'SC Paderborn 07',
       'SV Darmstadt 98', 'FC Ingolstadt 04', 'RB Leipzig',
       '1. FC Union Berlin'], dtype=object)

In [14]:
data['away_team_name'].unique()

array(['Borussia Mönchengladbach', '1. FSV Mainz 05', 'VfB Stuttgart',
       '1. FC Nürnberg', 'Borussia Dortmund', 'Arminia Bielefeld',
       'Hertha BSC', '1. FC Kaiserslautern', 'Bayer Leverkusen',
       'FC Bayern München', 'VfL Wolfsburg', 'FC Schalke 04',
       'Eintracht Frankfurt', 'MSV Duisburg', 'Hannover 96',
       'Hamburger SV', '1. FC Köln', 'Werder Bremen', 'Alemannia Aachen',
       'FC Energie Cottbus', 'VfL Bochum', 'FC Hansa Rostock',
       'Karlsruher SC', 'TSG 1899 Hoffenheim', 'SC Freiburg',
       'FC St. Pauli', 'FC Augsburg', 'Fortuna Düsseldorf',
       'SpVgg Greuther Fürth', 'Eintracht Braunschweig',
       'SC Paderborn 07', 'FC Ingolstadt 04', 'SV Darmstadt 98',
       'RB Leipzig', '1. FC Union Berlin'], dtype=object)

In [15]:
merged_df['home_team_name'].unique()

array(['Eintracht Frankfurt', 'Borussia Dortmund', '1. FC Union Berlin',
       '1. FC Köln', 'Borussia Mönchengladbach', 'VfL Wolfsburg',
       'VfL Bochum 1848', 'FC Augsburg', 'VfB Stuttgart',
       'FC Bayern München', 'Bayer 04 Leverkusen', 'RB Leipzig',
       'Sport-Club Freiburg', '1. FSV Mainz 05', 'TSG Hoffenheim',
       'Hertha BSC', 'FC Schalke 04', 'SV Werder Bremen',
       'DSC Arminia Bielefeld', 'VfL Bochum', 'SpVgg Greuther Fürth',
       'TSG 1899 Hoffenheim', 'Fortuna Düsseldorf', 'SC Paderborn 07',
       'Hannover 96', '1. FC Nürnberg', '1899 Hoffenheim', 'Hamburger SV',
       'SC Freiburg', 'Werder Bremen', 'FC Augsburg 1907',
       'FC Ingolstadt 04', 'SV Darmstadt 98', 'Eintracht Braunschweig',
       'Hertha BSC Berlin', '1. FC Kaiserslautern', 'FC St. Pauli',
       'FSV Mainz 05', 'Bayern München', 'Schalke 04', 'Bayer Leverkusen',
       'FC Energie Cottbus', 'Karlsruher SC', 'FC Hansa Rostock',
       'MSV Duisburg'], dtype=object)

In [16]:
merged_df['away_team_name'].unique()

array(['FC Bayern München', 'Bayer 04 Leverkusen', 'Hertha BSC',
       'FC Schalke 04', 'TSG Hoffenheim', 'SV Werder Bremen',
       '1. FSV Mainz 05', 'Sport-Club Freiburg', 'RB Leipzig',
       'VfL Wolfsburg', 'FC Augsburg', '1. FC Köln', 'Borussia Dortmund',
       '1. FC Union Berlin', 'VfL Bochum 1848', 'Eintracht Frankfurt',
       'Borussia Mönchengladbach', 'VfB Stuttgart', 'VfL Bochum',
       'SpVgg Greuther Fürth', 'DSC Arminia Bielefeld', 'SC Paderborn 07',
       'TSG 1899 Hoffenheim', 'Fortuna Düsseldorf', '1. FC Nürnberg',
       'Hannover 96', 'Werder Bremen', 'Hamburger SV', '1899 Hoffenheim',
       'SC Freiburg', 'SV Darmstadt 98', 'FC Ingolstadt 04',
       'FC Augsburg 1907', 'Eintracht Braunschweig', 'Hertha BSC Berlin',
       '1. FC Kaiserslautern', 'FC St. Pauli', 'Schalke 04',
       'Bayer Leverkusen', 'Bayern München', 'FSV Mainz 05',
       'Karlsruher SC', 'FC Energie Cottbus', 'FC Hansa Rostock',
       'MSV Duisburg'], dtype=object)

In [17]:
# Define a mapping of current names to new names
name_mapping = {
    '1899 Hoffenheim': 'TSG 1899 Hoffenheim',
    'TSG Hoffenheim': 'TSG 1899 Hoffenheim',
    'Bayer 04 Leverkusen': 'Bayer Leverkusen',
    'Bayern München': 'FC Bayern München',
    'DSC Arminia Bielefeld': 'Arminia Bielefeld',
    'FC Augsburg 1907': 'FC Augsburg',
    'FSV Mainz 05': '1. FSV Mainz 05',
    'Hertha BSC Berlin': 'Hertha BSC',
    'SV Werder Bremen': 'Werder Bremen',
    'Schalke 04': 'FC Schalke 04',
    'Sport-Club Freiburg': 'SC Freiburg',
    'VfL Bochum 1848': 'VfL Bochum'
}

# Replace the home team names
merged_df['home_team_name'] = merged_df['home_team_name'].replace(name_mapping)

# Do the same for the away team names
merged_df['away_team_name'] = merged_df['away_team_name'].replace(name_mapping)

In [18]:
merged_df

,matchday_nr,home_team_name,away_team_name,hist_home_team_win,hist_draw,hist_away_team_win,hist_goal_dif,season
0,1,Eintracht Frankfurt,FC Bayern München,24.0,22.0,56.0,-80.0,2022
1,1,Borussia Dortmund,Bayer Leverkusen,36.0,22.0,30.0,19.0,2022
2,1,1. FC Union Berlin,Hertha BSC,4.0,3.0,3.0,0.0,2022
3,1,1. FC Köln,FC Schalke 04,39.0,22.0,27.0,27.0,2022
4,1,Borussia Mönchengladbach,TSG 1899 Hoffenheim,8.0,12.0,10.0,6.0,2022
...,...,...,...,...,...,...,...,...
4891,34,Hannover 96,FC Energie Cottbus,4.0,0.0,4.0,-1.0,2008
4892,34,Borussia Dortmund,VfL Wolfsburg,12.0,7.0,3.0,18.0,2008
4893,34,Hamburger SV,Karlsruher SC,15.0,17.0,12.0,14.0,2008
4894,34,VfL Bochum,FC Hansa Rostock,7.0,4.0,9.0,-3.0,2008
4895,34,Eintracht Frankfurt,MSV Duisburg,27.0,14.0,15.0,33.0,2008

In [19]:
merged_df.to_csv('merged_df_cleaned.csv', index=False)